# Generated by Django 5.1.2 on 2024-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="eaddr",
            field=models.CharField(max_length=400),
        ),
    ]
